# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d3420ec719bbe336d4eec68b451bac7c3765b705bb729fe267c12b779ea714a2e6d378762e8f53fea285c9e2eb034982462b3185bc165820a8d64fbb15c01f

test:
  secret_key_base: 1aa5e87cd16946b109f4885d8211c509f4ff69d1d84a9a2c51a3341fc2fc6bb1698219e61775f0b11899e183e063415c423eca2cd39db37b2796aa90ef63ed82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: vagrant
